### ISSUE TITLE
Error line

### ISSUE THREAD

**Issue by andrisruse** [AbdouSam/arduino-sound-detector#4]
When we use the python script? I run the python script and it said "Indexerror: index 176400 is out of bounds for axis 0 with size 176400"
How can i fix it? In line 61

**Comment by AbdouSam** [comment]
The script is used to set these defines in `.ino` file, starting at line 21
```C
#define distace_duration_MAX  8000 //ms
#define distace_duration_MIN  900  //ms
#define peak_duration_MAX     1000 //ms
#define peak_duration_MIN     170  //ms
```
I don't remember exactly how it works, but the idea is to detect a pattern of Peaks in the sound, if there is a repeating peak of sound with a duration between peak_duration_MIN and MAX and it is repeating every distance_MIN and MAX, than it is likely to be a baby cry and not a sound of a motor cycle passing by.
In the script i took baby cries, `.wav` files , for example from : [soundjay website](https://www.soundjay.com/baby-crying-sound-effect.html) and try and detect the range of the duration of a peak in the sound and the distance between peaks.

For the error you are getting is because the `.wav` file you are using has a duration of less than 18 seconds. In the script _line 21_ the variable **data_time** sets the duration of the file you want to analyze. Just set the variable to whatever duration you want to analyze, it has to be less or equal to the file duration.
